routes:
    home:
        pattern: "/"
        controller: app.Controllers.DemoController
        action: helloAction

    hello:
        pattern: "/hello"
        controller: app.Controllers.DemoController
        action: templateAction

    content:
        pattern: "/content/{path_info:.*}"
        controller: app.Controllers.ContentController
        action: showAction

services:
    view:
        class: mvc.templates.MakoTemplates
        #class: mvc.templates.CheetahTemplates
