routes:
    home:
        pattern: "/"
        controller: HelloController
        action: helloAction

    content:
        pattern: "/content/{path_info:.*}"
        controller: ContentController
        action: showAction

services:
    view:
        class: mvc.templates.MakoTemplates
        #class: mvc.templates.CheetahTemplates
