routes:
    home:
        pattern: "/"
        controller: app.Controllers.DemoController
        action: indexAction

    mako:
        pattern: "/mako"
        controller: app.Controllers.DemoController
        action: makoAction

    cheetah:
        pattern: "/cheetah"
        controller: app.Controllers.DemoController
        action: cheetahAction

    content:
        pattern: "/content/{path_info:.*}"
        controller: app.Controllers.ContentController
        action: showAction

database:
    type: mysql
    host: deimos
    user: test
    password: 123123
    database: test

logfile: /tmp/log.log

services:
    view:
         class: MiniMVC.MakoTemplates
         params:
            - '%sys.container'

    log.handler:
        class: logbook.NestedSetup
        named_params:
            objects:
                - '@log.null_handler'
                - '@log.file_handler'

    log.null_handler:
        class: logbook.NullHandler

    log.file_handler:
        class: logbook.FileHandler
        params:
            - '%logfile'
        named_params:
            level: WARNING
