routes:
    home:
        pattern: "/"
        controller: app.Controllers.DemoController
        action: helloAction

    mako:
        pattern: "/mako"
        controller: app.Controllers.DemoController
        action: makoAction

    cheetah:
        pattern: "/cheetah"
        controller: app.Controllers.DemoController
        action: cheetahAction

    content:
        pattern: "/content/{path_info:.*}"
        controller: app.Controllers.ContentController
        action: showAction

services:
    view:
        class: MiniMVC.templates.MakoTemplates
        #class: MiniMVC.templates.CheetahTemplates
