sys.routes:
    home:
        pattern: "/"
        controller: app.Controllers.DemoController
        action: indexAction

    mako:
        pattern: "/mako"
        controller: app.Controllers.DemoController
        action: makoAction

    cheetah:
        pattern: "/cheetah"
        controller: app.Controllers.DemoController
        action: cheetahAction

    content:
        pattern: "/content/{path_info:.*}"
        controller: app.Controllers.ContentController
        action: showAction

sys.database:
    host: deimos
    user: test
    password: 123123
    database: test

services:
    view:
         class: MiniMVC.MakoTemplates
         params:
            - '%sys.container'
        #class: MiniMVC.view.CheetahTemplates
